-- OpenAPI schema
DROP TABLE IF EXISTS open_api_doc;
DROP TABLE IF EXISTS open_call_log;
DROP TABLE IF EXISTS open_app_api;
DROP TABLE IF EXISTS open_api;
DROP TABLE IF EXISTS open_app;

CREATE TABLE open_app (
  s_id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  app_name        VARCHAR(100) NOT NULL,
  app_key         VARCHAR(64)  NOT NULL UNIQUE,
  app_secret      VARCHAR(128) NOT NULL,
  contact         VARCHAR(100) NULL,
  status          smallint DEFAULT 1,
  expire_time     timestamp NULL,
  remark          VARCHAR(500) NULL,
  create_time     timestamp DEFAULT CURRENT_TIMESTAMP,
  update_time     timestamp DEFAULT CURRENT_TIMESTAMP ,
  s_status        smallint DEFAULT 1,
  s_is_del        smallint DEFAULT 1,
  s_created_time  timestamp DEFAULT CURRENT_TIMESTAMP,
  s_updated_time  timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE open_api (
  s_id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  api_name        VARCHAR(100) NOT NULL,
  api_path        VARCHAR(200) NOT NULL UNIQUE,
  method          VARCHAR(10)  DEFAULT 'POST',
  target_url      VARCHAR(500) NOT NULL,
  timeout_ms      INT DEFAULT 5000,
  status          smallint DEFAULT 1,
  need_sign       smallint DEFAULT 1,
  description     VARCHAR(500) NULL,
  req_example     TEXT NULL,
  resp_example    TEXT NULL,
  create_time     timestamp DEFAULT CURRENT_TIMESTAMP,
  update_time     timestamp DEFAULT CURRENT_TIMESTAMP ,
  s_status        smallint DEFAULT 1,
  s_is_del        smallint DEFAULT 1,
  s_created_time  timestamp DEFAULT CURRENT_TIMESTAMP,
  s_updated_time  timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE open_app_api (
  s_id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  app_id          BIGINT NOT NULL,
  api_id          BIGINT NOT NULL,
  create_time     timestamp DEFAULT CURRENT_TIMESTAMP,
  update_time     timestamp DEFAULT CURRENT_TIMESTAMP ,
  s_status        smallint DEFAULT 1,
  s_is_del        smallint DEFAULT 1,
  s_created_time  timestamp DEFAULT CURRENT_TIMESTAMP,
  s_updated_time  timestamp DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (app_id, api_id)
);

CREATE TABLE open_call_log (
  s_id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  trace_id        VARCHAR(64)  NOT NULL,
  app_key         VARCHAR(64)  NULL,
  app_name        VARCHAR(100) NULL,
  api_path        VARCHAR(200) NULL,
  method          VARCHAR(10)  NULL,
  req_headers     TEXT NULL,
  req_body        TEXT NULL,
  resp_code       INT NULL,
  resp_headers    TEXT NULL,
  resp_body       TEXT NULL,
  cost_ms         INT NULL,
  status          smallint NULL,
  error_msg       VARCHAR(500) NULL,
  client_ip       VARCHAR(64)  NULL,
  call_time       timestamp DEFAULT CURRENT_TIMESTAMP,
  create_time     timestamp DEFAULT CURRENT_TIMESTAMP,
  update_time     timestamp DEFAULT CURRENT_TIMESTAMP ,
  s_status        smallint DEFAULT 1,
  s_is_del        smallint DEFAULT 1,
  s_created_time  timestamp DEFAULT CURRENT_TIMESTAMP,
  s_updated_time  timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE open_api_doc (
  s_id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  app_id          BIGINT NULL,
  doc_title       VARCHAR(100) NULL,
  doc_version     VARCHAR(20) NULL,
  api_ids         VARCHAR(500) NULL,
  html_content    text NULL,
  create_time     timestamp DEFAULT CURRENT_TIMESTAMP,
  update_time     timestamp DEFAULT CURRENT_TIMESTAMP ,
  s_status        smallint DEFAULT 1,
  s_is_del        smallint DEFAULT 1,
  s_created_time  timestamp DEFAULT CURRENT_TIMESTAMP,
  s_updated_time  timestamp DEFAULT CURRENT_TIMESTAMP
);





